[package]
name = "fn_pipe"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
doctest = false
name = "fn_pipe"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
fn_pipe_proc = { workspace = true }