stages:
  - build
  - syntax-check
  - test-syntax
  - test-middle
  - test-backend
  - test-compiler

# Common setup template
.common_setup:
  before_script:
    - rustup override set nightly

# Build stage that others can depend on
build:
  extends: .common_setup
  stage: build
  script:
    - cargo clean  # Only clean once at the beginning
    - cargo build --verbose
  artifacts:
    paths:
      - target/debug/
    exclude:
      - target/debug/compiler
    expire_in: 1 hour

# Syntax Check Stage
syntax-check:
  extends: .common_setup
  stage: syntax-check
  script:
    - cargo check --verbose
  dependencies:
    - build
  artifacts:
    paths:
      - target/debug/
    expire_in: 1 hour

test-syntax:
  extends: .common_setup
  stage: test-syntax
  script:
    - cargo test --package syntax --verbose
  dependencies:
    - build
  artifacts:
    paths:
      - target/debug/
    expire_in: 1 hour

test-middle:
  extends: .common_setup
  stage: test-middle
  script:
    - cargo test --package middle --verbose
  dependencies:
    - build
  artifacts:
    paths:
      - target/debug/
    expire_in: 1 hour

test-backend:
  extends: .common_setup
  stage: test-backend
  script:
    - cargo test --package backend --verbose
  dependencies:
    - build
  artifacts:
    paths:
      - target/debug/
    expire_in: 1 hour

# Test Compiler Crate
test-compiler:
  stage: test-compiler
  script:
    - rustup override set nightly
    - cargo test --package compiler --verbose
    - rm -f target/debug/compiler
  dependencies:
    - test-syntax
    - test-middle
    - test-backend
  artifacts:
    paths:
      - target/debug/
    expire_in: 1 hour
