stages:
  - syntax-check
  - test-syntax
  - test-middle
  - test-backend
  - test-compiler

# Cache configuration to speed up builds
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - target/
    - .cargo/registry
    - .cargo/git

# Syntax Check Stage
syntax-check:
  stage: syntax-check
  script:
    - rustup override set nightly
    - cargo check --verbose
  artifacts:
    paths:
      - target/debug/
    expire_in: 1 week

# Test Syntax Crate
test-syntax:
  stage: test-syntax
  script:
    - rustup override set nightly
    - cargo test --package syntax --verbose
  dependencies:
    - syntax-check
  artifacts:
    paths:
      - target/debug/
    expire_in: 1 week

# Test Middle Crate
test-middle:
  stage: test-middle
  script:
    - rustup override set nightly
    - cargo test --package middle --verbose
  dependencies:
    - syntax-check
    - test-syntax
  artifacts:
    paths:
      - target/debug/
    expire_in: 1 week

# Test Backend Crate
test-backend:
  stage: test-backend
  script:
    - rustup override set nightly
    - cargo test --package backend --verbose
  dependencies:
    - syntax-check
    - test-middle
  artifacts:
    paths:
      - target/debug/
    expire_in: 1 week

# # Test Compiler Crate
# test-compiler:
#   stage: test-compiler
#   script:
#     - rustup override set nightly
#     - cargo test --package compiler --verbose
#   dependencies:
#     - test-syntax
#     - test-middle
#     - test-backend
#   artifacts:
#     paths:
#       - target/debug/
#     expire_in: 1 week
