stages:
  - build
  - test

# Cache configuration to speed up builds
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - target/
    - .cargo/registry
    - .cargo/git

# Build stage
build:
  stage: build
  script:
    - rustup override set nightly
    - cargo build --verbose
  artifacts:
    paths:
      - target/debug/
    expire_in: 1 week

# Test stage
test:
  stage: test
  script:
    - rustup override set nightly
    - cargo test --verbose
  dependencies:
    - build
