[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
syntax = { path = "../syntax" }
middle = { path = "../middle" }
util = { path = "../util" }
once_cell = "1.20.3"

[lints]
workspace = true
