[package]
name = "compiler"
version = "0.1.0"
edition = "2024"
publish = false

[lints]
workspace = true

[dependencies]
syntax = { workspace = true }
middle = { workspace = true }
backend = { workspace = true }
ariadne = { workspace = true }

chumsky = { workspace = true, features = [
    "std",
    "stacker",
    "memoization",
    "pratt",
    "regex",
    "nightly",
] }
clap = { workspace = true, features = ["derive"] }


