[package]
name = "compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
syntax = { path = "../syntax" }
middle = { path = "../middle" }
backend = { path = "../backend" }
ariadne = "0.5.0"

chumsky = { features = [
  "std",
  "stacker",
  "memoization",
  "pratt",
  "regex",
  "nightly",
], git = "https://github.com/zesterer/chumsky", rev = "282bf5e" } # currently latest chumsky commit

[lints]
workspace = true
